Belinda_NextJs_Sprint3_Add_Profile_Icon
SeattleColleges/belindas-closet-nextjs pull request #266
Opened 2024-03-14 20:53 UTC by MuhammadNSC

This is related to #235 I added a Profile Icon to the Navbar that has a link to Account, Profile and Signin page. I tried adding the Signout page also but I was struggling with the linking it to the signout authentication so I left it out. 

This is the profile icon in the navbar
<img width="410" alt="Screenshot 2024-03-14 at 1 45 29 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/117953848/4ff5e81e-69a1-426d-83d8-1be56ba83334">
This is the the Profile dropdown
<img width="175" alt="Screenshot 2024-03-14 at 1 45 46 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/117953848/6bbc7284-949a-4fbd-a5e4-08f2d101cd43">
This is the Profile Page when click from the dropdown
<img width="935" alt="Screenshot 2024-03-14 at 1 46 04 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/117953848/cc347838-0146-4423-9384-6070786b633f">
This the Account Page when click from the dropdown (Nothing to show at the moment)
<img width="912" alt="Screenshot 2024-03-14 at 1 46 18 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/117953848/71324abf-91b8-4d38-a218-d17909f011e6">
This the the Signin Page when click from the dropdown
<img width="909" alt="Screenshot 2024-03-14 at 1 46 26 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/117953848/7218cc0c-ef30-4a1e-8045-7048eaba49a8">

2024-03-15 20:26 UTC, tinpham5614 commented
The Profile Menu displays as default which shouldn't be.
You can remove the hyperlink in the menu items to make it look better.

![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/70edbeb5-00d1-4687-9766-ce62ba083064)

2024-03-18 07:38 UTC, taylorpapke requested changes
Similar to what @tinpham5614 is saying above, I think we should do the following here:
- Change "sign in" to "sign out" (even if it doesn't do anything).
- Delete "profile" and just have "account" as a link to creator, admin and user (placeholder) profile.

2024-04-16 16:42 UTC, Seiyaroo commented
@taylorpapke @tinpham5614 do we know if this is needed or being worked on anymore? Or should we close it?

2024-04-16 16:47 UTC, tinpham5614 commented
@Seiyaroo I implemented this on my side and will create a PR for this issue if no one works on it.

2024-04-19 02:23 UTC, Asfand00 commented
I can confirm as well that the icon works and shows on my end: 
![belinda-closet-icon](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91708459/8377592d-5450-4e4d-a821-3bf21f48390a)

2024-04-19 03:42 UTC, tinpham5614 commented
I added things on top of this PR with another PR.
I will close this PR and redirect it to #297.

2024-04-19 03:42 UTC, closed without merging