<User Story: Contact Page>_<Sprint 5>_<The Contact Page has been create>(No routes)
SeattleColleges/belindas-closet-nextjs pull request #285
Opened 2024-04-17 04:23 UTC by kaimanasse15

This user story has no testing with routes. It look okay a little for now.

2024-04-17 20:29 UTC, cshimm commented
This looks good, although we might want to consider the naming for the directory to be all lowercase letters as the routes appear to be case-sensitive, meaning routing to /contact-page is not the same as routing to /Contact-Page. This would also keep with the "lowercase-words-separated-by-dashes" convention. Just a thought.

2024-04-17 20:32 UTC, kaimanasse15 commented
Hi @cshimm, Thank you for your advise!. I will fix that and update again!

2024-04-17 20:53 UTC, nickolasram commented
Good afternoon. @kaimanasse15 . I'm going to ask you make some revisions before approving this request. I know, these projects are a lot to jump into all of a sudden. Hopefully, my requests are understandable and can help you get more comfortable working on this project. And feel free to ask me any clarifying questions :) 
1. If this is just an update to the changes you made on your other pull request, can you delete your older pull request?
2. can you reformat the name of this pull request? If you look at the other pull requests currently open, you can see our usual  naming convention. You don't need the angular brackets.
You can also look at older pull requests by clicking here on the pull request page
![Screenshot 2024-04-17 131134](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91910852/2ee6ec42-e02a-43a2-bd14-990ef17b4ead)

3. can you request reviews from others when you submit a pull request? You can do this on the right side of this page by clicking the little gear next to "Reviewers". You can select a few people you'd like to review this PR and I'd suggest you include SeattleColleges/Leadership in those selections. That will tag all the members of the leadership team without you having to select each of them one by one.
4. can you add a link to the contact page to the navbar? you can do this in the components/ Navbar.tsx file.  You just have to add the name of the page and the URL address to these two arrays.
![Screenshot 2024-04-17 131448](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91910852/b3c97bdc-1162-4709-b3a5-e46c651e0c3c)

As I said, this is a lot to jump into. Hopefully this all helps you get into the flow of things!

2024-04-17 20:54 UTC, nickolasram requested changes
Good afternoon. @kaimanasse15 . I'm going to ask you make some revisions before approving this request. I know, these projects are a lot to jump into all of a sudden. Hopefully, my requests are understandable and can help you get more comfortable working on this project. And feel free to ask me any clarifying questions :) 
1. If this is just an update to the changes you made on your other pull request, can you delete your older pull request?
2. can you reformat the name of this pull request? If you look at the other pull requests currently open, you can see our usual  naming convention. You don't need the angular brackets.
You can also look at older pull requests by clicking here on the pull request page
![Screenshot 2024-04-17 131134](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91910852/2ee6ec42-e02a-43a2-bd14-990ef17b4ead)

3. can you request reviews from others when you submit a pull request? You can do this on the right side of this page by clicking the little gear next to "Reviewers". You can select a few people you'd like to review this PR and I'd suggest you include SeattleColleges/Leadership in those selections. That will tag all the members of the leadership team without you having to select each of them one by one.
4. can you add a link to the contact page to the navbar? you can do this in the components/ Navbar.tsx file.  You just have to add the name of the page and the URL address to these two arrays.
![Screenshot 2024-04-17 131448](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91910852/b3c97bdc-1162-4709-b3a5-e46c651e0c3c)

As I said, this is a lot to jump into. Hopefully this all helps you get into the flow of things!

2024-04-18 01:14 UTC, MuhammadNSC commented
This is a good start but the code only provides a basic structure for the contact page. As requested I think you should change to naming to lower case letters to match the naming of the rest of the directories. Other thank that I think you are off to a great start.

2024-04-18 16:47 UTC, kaimanasse15 commented
@tinpham5614, will you have some time to hope on to see my route? The place holder is error. Nick didn''t find any problem with my route. Thank you

2024-04-18 19:28 UTC, tinpham5614 commented on app/Contact-Page/page.tsx
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/148094ee-b8fb-40df-be92-571de1829979)
The folder name should be lowercase.

2024-04-18 19:32 UTC, tinpham5614 commented on app/admin-page/page.tsx
Do we want the admin page to include the contact button here?

2024-04-18 19:34 UTC, tinpham5614 commented on components/Navbar.tsx
> +const links = ["/", "/auth/sign-in", "/donation-info","/contact"];
There is an inconsistency between the element in the links array and the contact page folder, which is causing the contact-page to be unresponsive.

2024-04-18 19:35 UTC, kaimanasse15 commented on app/Contact-Page/page.tsx
Hi Tin,
I changed the name to lowe case also but it doesn't work

2024-04-18 19:42 UTC, tinpham5614 commented on app/Contact-Page/page.tsx
Please read through all the comments.
Here is the result if you fix it:

[Screencast from 2024-04-18 12-40-23.webm](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/b9b1b03c-0008-4524-8a8a-0339b543d690)

2024-04-19 02:46 UTC, Asfand00 commented
This is the contact page that I am seeing on my end:
![belinda-closet-contact-page](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91708459/a4381344-1eb8-4746-a839-1dadb607ab8a)
Looks okay and barebones, definitely needs routing as mentioned by others, but good start

2024-04-19 04:00 UTC, gitbiruk2010 commented on app/admin-page/page.tsx
Good job here @kaimanasse15. once the button is linked to the desired route, it's gonna look good. additionally, while the style applied directly to the button esures it stands out.

2024-04-21 00:32 UTC, nickolasram commented on components/Navbar.tsx
This is almost ready to squash and merge! Can you add "Contact" and "/Contact-Page" to these arrays in Navbar.tsx like the rest of the navbar items?
![Screenshot 2024-04-20 173033](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91910852/b54d8f3a-58ed-405a-ba10-25e17737b474)

Nice job btw of merging main into your branch to keep it up to date and avoid merge conflicts.

2024-04-21 00:46 UTC, kaimanasse15 commented on components/Navbar.tsx
@nickolasram. This is weird. I fixed this problem and submitted it in class on the last Thursday. Thank you for your checking! I commit it again!

2024-04-21 05:52 UTC, nickolasram commented on components/Navbar.tsx
@kaimanasse15 did you run "git push" after making the commit?

2024-04-21 05:57 UTC, kaimanasse15 commented on components/Navbar.tsx
@nickolasram Yes! I did the git push. Please take a look at my image.
[Uploading Untitled document.pdf…]()

2024-04-21 05:58 UTC, kaimanasse15 commented on components/Navbar.tsx
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91504156/5dd1bd91-d773-4508-8612-1eb1d5d54283)

2024-04-21 06:55 UTC, nickolasram commented on components/Navbar.tsx
@kaimanasse15 Is that your current version of this branch that you have saved locally? If it is, can you test to make sure that it works?

2024-04-21 07:00 UTC, kaimanasse15 commented on components/Navbar.tsx
@nickolasram it is weird. It works yesterday but I run it again and it shows
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91504156/f966f94b-33a8-4a4a-bf82-1768df677921)

2024-04-21 07:03 UTC, nickolasram commented on components/Navbar.tsx
@kaimanasse15 try running "npm run dev" instead

2024-04-21 07:05 UTC, kaimanasse15 commented on components/Navbar.tsx
@nickolasram Thanks Nick! it works on my branch
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91504156/a5d08e9c-aea2-4585-9c4d-518a973f9518)

2024-04-21 07:07 UTC, nickolasram commented on components/Navbar.tsx
If it's for sure working locally, try running the following:
git add .
git commit -m "contact commit"
git push

2024-04-21 07:09 UTC, kaimanasse15 commented on components/Navbar.tsx
@nickolasram Did you see my commit yet?

2024-04-21 07:11 UTC, nickolasram commented on components/Navbar.tsx
@kaimanasse15 yes, I see it. Give me one second to test it works 👌

2024-04-21 07:22 UTC, nickolasram commented on components/Navbar.tsx
@kaimanasse15 So the navbar file has been successfully updated. However, I'm getting an error whenever I try to go to the contact page whenever I click on the link in the navbar. This is because in navbar.tsx you've written "/contact-page", but the folder that contains the contact page file is called Contact-Page. The difference in capitalization matters. Can you rename the contact page folder to be lower case (contact-page) and then run these three commands again:
git add .
git commit -m "fixed capitalization"
git push

2024-04-21 07:24 UTC, kaimanasse15 commented on components/Navbar.tsx
@nickolasram that page has been fix the name also. I don't why it doesn't update but I will do the commit again
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91504156/466bf934-ac97-45c4-a5b3-0ba8e294e7cb)

2024-04-21 07:25 UTC, kaimanasse15 commented on components/Navbar.tsx
I am unable to do the commit again since nothing changed
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91504156/670e09df-7483-49a5-86f6-1e07a788986b)

2024-04-21 07:30 UTC, nickolasram commented on components/Navbar.tsx
Can you try changing something that doesn't matter and then running the add, commit, push commands again? Like, add an extra space at the end of a line.

2024-04-21 07:32 UTC, nickolasram commented on components/Navbar.tsx
Just something that doesn't change how anything works, but a change github will recognize.

2024-04-21 07:36 UTC, kaimanasse15 commented on components/Navbar.tsx
Please check again Nick! I did the double commit to see if it works

2024-04-21 08:02 UTC, nickolasram commented on components/Navbar.tsx
I tried doing the same thing on my end. Didn't change the name of the folder here either. I was, however, able to rename the folder using the github web editor. Can you just real quickly run a "git pull" for this branch and test to make sure that navbar works for you too? You might have to restart VS Code to get it to recompile and work.

2024-04-21 08:04 UTC, kaimanasse15 commented on components/Navbar.tsx
It works for me.

2024-04-21 08:08 UTC, nickolasram commented on components/Navbar.tsx
Great! Okay, I'll remove my change request. Can you go through and hit all the "Resolve Conversation" buttons on this page? Then you should be able to squash and merge this into main 😄 Great job making it through doing all this tedious work! it definitely ended up being a bit tricky.

2024-04-21 08:09 UTC, nickolasram approved these changes

2024-04-21 08:15 UTC, nickolasram commented
@Asfand00 if you're still awake, can you try fetching this branch to your machine and testing to make sure the Contact button in the nav bar links to the placeholder contact page and approve this pull request if it does?

2024-04-22 21:28 UTC, taylorpapke approved these changes
LGTM
<img width="1327" alt="Screenshot 2024-04-22 at 2 27 27 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/94101953/719deef7-6d95-4ad9-bf66-5a1b2492deb7">

2024-04-23 04:26 UTC, Asfand00 commented
I don't think I have authority to approve this PR @nickolasram but I tested the page again, this is the result:
![belinda-closet-contact-page2](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91708459/1c8f9d93-2d15-489f-9711-c5fee93ac3a3)
I can personally approve that this page works as it is

2024-04-23 08:04 UTC, nickolasram commented
@Asfand00 try going to the "Files Changed" tab and see if you can click on the green "Review Changes" button

2024-04-23 08:55 UTC, Asfand00 approved these changes

2024-04-23 09:23 UTC, nickolasram commented
@taylorpapke can this PR be manually merged? Everything works but Kai's commits weren't signed.

2024-04-23 18:19 UTC, brinkbrink commented
@kaimanasse15 Please reach out to @tinpham5614 or @bcko to troubleshoot signing commits. You also have to remember to sign the commits after you've created your key. It may be helpful to look into auto-signing your commits (which is what I do).

Here is a good bit of advice from [GitHub's docs](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits):

To configure your Git client to sign commits by default for a local repository, in Git versions 2.0.0 and above, run `git config commit.gpgsign true`. To sign all commits by default in any local repository on your computer, run `git config --global commit.gpgsign true`.

To store your GPG key passphrase so you don't have to enter it every time you sign a commit, we recommend using the following tools:

For Mac users, the [GPG Suite](https://gpgtools.org/) allows you to store your GPG key passphrase in the macOS Keychain.
For Windows users, the [Gpg4win](https://www.gpg4win.org/) integrates with other Windows tools.
You can also manually configure [gpg-agent](http://linux.die.net/man/1/gpg-agent) to save your GPG key passphrase, but this doesn't integrate with macOS Keychain like ssh-agent and requires more setup.

2024-04-23 18:20 UTC, merged