belindas-closet-nextjs_5_294_Dashboard Page
SeattleColleges/belindas-closet-nextjs pull request #304
Opened 2024-04-19 23:42 UTC by BradleyCharles

Resolves issue #294 

Added a landing dashboard page with a link in the navbar.

![dashboard1](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/67434992/2cf970de-b681-4ada-83df-b39bb16d2850)
![dashboard2](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/67434992/45662132-861a-470c-a378-0cb5da592939)

2024-04-20 00:53 UTC, alasali1 reviewed
It looks good to me. I was able to see the dashboard button, and navigate to the dashboard page successfully.

![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/77362461/02803ba0-df42-4d47-a6ff-34a559f55942)

![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/77362461/65cec360-dfcf-4f2b-8fec-a0b5534d7e12)

2024-04-20 00:55 UTC, alasali1 approved these changes

2024-04-20 02:23 UTC, nwm516 commented
It worked for me for the most part when replicating it in my local environment. However, I did notice some routing issues when navigating to the Dashboard from certain pages.


https://github.com/SeattleColleges/belindas-closet-nextjs/assets/36825393/b5092cdb-fe38-4b83-bbf3-98b7983a0cba

Certain pages seemed to get there just fine, whereas others had some unexpected output, as you can see. Probably comes down to routing issues that may extend beyond the scope of your user story but felt it was worth mentioning. I imagine that since the Dashboard will be an exclusive feature to Admins that these issues may be moot, in the long run.

2024-04-21 18:00 UTC, cshimm commented
It looks like the 404 is happening because of the missing '/' in front of 'dashboard' in the links array. adding that fixed that 404 problem 
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/13278479/becb51a2-ffac-48ce-8d30-c23375efdaa5)

2024-04-22 21:41 UTC, taylorpapke approved these changes
Looks great!
<img width="1263" alt="Screenshot 2024-04-22 at 2 40 21 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/94101953/a70f59e7-01bf-478b-b758-11f90353603d">

2024-04-23 03:31 UTC, tinpham5614 commented on app/dashboard/page.module.css
Since we are using MUI for styling, we may not require a CSS file.

2024-04-23 03:34 UTC, tinpham5614 requested changes

2024-04-23 03:34 UTC, tinpham5614 commented on components/Navbar.tsx
> +  "dashboard",
There seems to be a routing error due to a missing forward slash "/". Adding the forward slash should resolve the issue.

2024-04-23 03:34 UTC, tinpham5614 commented on app/dashboard/page.module.css
Since we are using MUI for styling, we may not require a CSS file.

2024-04-23 18:15 UTC, BradleyCharles commented on app/dashboard/page.module.css
I removed the CSS file as it was not needed

2024-04-23 18:25 UTC, tinpham5614 commented
There are conflicts due to codes are not up-to-date.

2024-04-23 18:28 UTC, brinkbrink commented
Looks like there are issues with signing commits here. Pro-tip: You also have to remember to sign the commits after you've created your key. It may be helpful to look into auto-signing your commits (which is what I do).

Here is a good bit of advice from [GitHub's docs](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits):

To configure your Git client to sign commits by default for a local repository, in Git versions 2.0.0 and above, run `git config commit.gpgsign true`. To sign all commits by default in any local repository on your computer, run `git config --global commit.gpgsign true`.

To store your GPG key passphrase so you don't have to enter it every time you sign a commit, we recommend using the following tools:

For Mac users, the [GPG Suite](https://gpgtools.org/) allows you to store your GPG key passphrase in the macOS Keychain.
For Windows users, the [Gpg4win](https://www.gpg4win.org/) integrates with other Windows tools.
You can also manually configure [gpg-agent](http://linux.die.net/man/1/gpg-agent) to save your GPG key passphrase, but this doesn't integrate with macOS Keychain like ssh-agent and requires more setup.

2024-04-23 18:28 UTC, merged