belindas-closet-nextjs_6_323_mui-creator-page
SeattleColleges/belindas-closet-nextjs pull request #343
Opened 2024-05-03 04:23 UTC by nwm516

Resolves #323 

Integrate Material UI on the Creator page.

https://github.com/SeattleColleges/belindas-closet-nextjs/assets/36825393/80bd082a-8d3d-4ecc-a5bc-bfeed0810e78

Before: 
![Admin Page](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/36825393/35866600-bcff-4fbb-97b1-0c6fa01327a1)  ![Placeholder Creator Page](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/36825393/17644b44-e1e1-4c2d-a01b-5ffd0c0c9a07)

After:
![Admin Page MUI](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/36825393/e8b92e58-31a7-4867-a066-3a4cc4066303) ![Creator Page MUI](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/36825393/65db523d-0ba1-48a0-b95c-d6a1e7640809)

2024-05-05 21:40 UTC, taylorpapke commented
Same as your other PR. Don't know if you were going to do this but looks like you just need to do an npm install of the 2 modules shown in the error message below and then push to this PR branch:
<img width="958" alt="Screenshot 2024-05-05 at 2 35 20 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/94101953/295b8d3d-0bd0-4280-9095-2b6c655b8084">

2024-05-06 00:43 UTC, MaddasaHatter submitted a review, later dismissed
Looks like it is getting hung up on one of the checks and failing. I'm also running into the same issue as Taylor when testing the build. 


![Screenshot_20240505_173611_GitHub.jpg](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/52189566/59356400-18bb-4c7d-adaa-c10cee80304e)

2024-05-10 03:17 UTC, Asfand00 submitted a review, later dismissed
/This is what the creator page looks on my end: 
![creator-page2](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91708459/6862d3ce-be5e-4545-9fae-7f25eb174b99)
For the things circled in red, is that intentional of how it should look, if so it looks kinda hard to see if it's supposed to be purple.

Also when i click on the products dropdown on navbar this shows up:
![products](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91708459/497ec81b-29d4-487a-a3f0-316f4be536d7)
looks like that needs to be fixed

These errors might also be on my end only (not sure), I use npm not yarn, so I had to adjust to those changes and making sure dependecies were right. 

Though it seems your still having the issue with the check not going through because your missing some modules that need to be installed so it seems at the moment that issue is still there.

2024-05-10 03:25 UTC, Asfand00 reviewed
Use my earlier comment as general feedback without explicit approval (this is what i meant to do instead) the requested changes were already requested basically.

2024-05-10 06:44 UTC, taylorpapke commented
I didn't notice the yarn.lock file that @Asfand00 mentioned. I don't know too much about yarn but after a quick search online, it appears that having 2 package managers (npm and yarn) could potentially lead to dependency conflicts. I'm not sure if that's the case here but we might want to ask ourselves if this is something we want to introduce at this point @brinkbrink

2024-05-10 15:38 UTC, brinkbrink commented
> I didn't notice the yarn.lock file that @Asfand00 mentioned. I don't know too much about yarn but after a quick search online, it appears that having 2 package managers (npm and yarn) could potentially lead to dependency conflicts. I'm not sure if that's the case here but we might want to ask ourselves if this is something we want to introduce at this point @brinkbrink

@taylorpapke Yes, multiple package managers can, like you said, lead to conflicts and add unnecessary complexity. That's actually why there's a failing check here. If you click the "Details" link next to the failing check you can see that here:

<img width="809" alt="Screenshot 2024-05-10 at 8 28 28 AM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/80282265/5c2c4c28-c17a-4b35-ac5c-5611c2b105ed">

While it's possible to resolve these dependencies manually, I don't think anybody wants to do that. Especially when you look at the size of that yarn.lock, woof! 

We also had a discussion a while back about not using [dependabot](https://github.com/dependabot) anymore because we wanted to produce stable releases so let's also be careful about changing the package.json unless it's necessary.

<img width="806" alt="Screenshot 2024-05-10 at 8 30 58 AM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/80282265/e308e5cf-9b54-484a-beec-748946a3f125">

This is stuff that not everybody has been exposed to/learned about so I'm kind of glad you did this @nwm516 so we can all use this as a learning experience.

2024-05-10 15:44 UTC, brinkbrink requested changes
There are definitely benefits to using yarn and if you think this is a direction the team should go in we should have a team discussion but for now we are using npm as our package manager. Please make appropriate changes. Feel free to reach out to @tinpham5614, @IsaacJrTypes or @cshimm for help with these changes if you hit a roadblock. Hopefully it isn't too painful.

2024-05-10 17:12 UTC, nwm516 commented
Thanks everyone for the feedback. I put this on the backburner with the intent of returning once I had found the courage to try again, heh. 

Makes sense on dependencies from yarn and npm conflicting, though, like you said @brinkbrink, this is something that is wholly new to me, so my understanding of how this all plays together is still very fresh.

I'll make the appropriate changes again with integrating npm solely and will reach out to the appropriate team members with any difficulties I encounter here on out.

2024-05-10 19:33 UTC, brinkbrink commented
> Thanks everyone for the feedback. I put this on the backburner with the intent of returning once I had found the courage to try again, heh.
> 
> Makes sense on dependencies from yarn and npm conflicting, though, like you said @brinkbrink, this is something that is wholly new to me, so my understanding of how this all plays together is still very fresh.
> 
> I'll make the appropriate changes again with integrating npm solely and will reach out to the appropriate team members with any difficulties I encounter here on out.

Sounds good! Walking away and coming back is sometimes the best solution, I've been there...quite a few times haha

2024-05-16 08:26 UTC, taylorpapke approved these changes

2024-05-17 02:38 UTC, Asfand00 approved these changes
LGTM! everything checks out on my end 
![creator-page3](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91708459/68d44e88-78f6-4ece-8f09-b4209f3b881b)

2024-05-17 04:28 UTC, el-riber approved these changes
you code looks great!

2024-05-17 04:50 UTC, intisarosman1 approved these changes
Everything looks good!
![Screenshot 2024-05-16 214917](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/77607212/e8cb658a-560f-4f0a-91ab-45e5583e0a14)

2024-05-20 03:36 UTC, gitbiruk2010 commented on app/creator-page/page.tsx
The updates to the creator-page/page.tsx are looking good! The use of Material-UI components like Button, Typography, and ButtonGroup greatly enhances the UI, making it more user-friendly and visually appealing. The refactor to remove boilerplate code and streamline the component structure is a good improvement. Additionally, the well-organized addition of placeholders and clear navigation buttons simplifies the user journey. Great job!

2024-05-21 06:48 UTC, heosman approved these changes
It looks good now and the buttons are routing to the correct pages.

2024-05-22 00:26 UTC, nickolasram approved these changes
Great job sorting everything out! Everything looks great on my end

2024-05-22 04:10 UTC, taylorpapke commented
@brinkbrink Can you approve changes? It looks like 3 approvals have been met for this PR.

2024-05-22 16:04 UTC, brinkbrink approved these changes

2024-05-22 16:04 UTC, merged