Belinda_Next_JS_Sprint_7_386_Fix_Product_Tile_Sizing
SeattleColleges/belindas-closet-nextjs pull request #398
Opened 2024-05-23 20:11 UTC by MuhammadNSC

Adjust Tile sizing for product page to all be consistent
<img width="207" alt="Screenshot 2024-05-23 at 1 10 27 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/117953848/bea9c92e-6a40-4762-9b2b-9009d3957a28">

2024-05-23 21:40 UTC, Diego-Cano commented
The screenshot shared clearly shows the discrepancy in the product tiles, particularly with the size and layout of the "Shoes" tiles. The updated code solves the tiles to have uniform sizing, which enhances the overall visual coherence of the product page. This adjustment can be seen in the commit where the tile sizes are modified to align better with the design guidelines.

 I observed that there are conflicts in the package-lock.json and package.json files. These need to be resolved before merging the changes. The consistency in the tile sizes not only enhances the user exp. but also maintains the integrity of the design, which is crucial for user satisfaction. Once the conflicts are resolved and the draft is finalized, this update will significantly improve the UI of the product page.

Also, I found this great link for solving conflicts on github: (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts).

2024-05-23 22:11 UTC, gitbiruk2010 commented on app/category-page/[categoryId]/page.tsx
The adjustments to the tile sizes ensure a more consistent and visually appealing layout across different screen sizes. Great work on enhancing the user experience for the product page!

2024-05-25 23:46 UTC, tinpham5614 commented
The Product Card looks good now.
I'm considering whether we should use columns and rows, so users don't have to scroll through each one.

![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/3b64c91e-ae9b-42cb-80fe-51693c87d05f)

2024-05-27 17:01 UTC, brinkbrink commented
Is this still a draft request @MuhammadNSC? Looks like some of this work could be ready to merge after resolving some conflicts in the package-lock.json (should be easy to resolve, just use whatever is from main).

2024-05-29 04:13 UTC, taylorpapke approved these changes
Tile sizing is consistent on all product category pages:
<img width="579" alt="Screenshot 2024-05-28 at 9 10 10 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/94101953/715183be-1d8a-4480-9348-779f7177dd97">

2024-05-29 04:56 UTC, MuhammadNSC commented
@brinkbrink I've the issues I was having whit this PR. It can now be merged.
@tinpham5614 having columns will be a good idea especially when there is alot more products on display

2024-05-29 05:17 UTC, Alzavio reviewed
Is the height difference across pages a problem? If not, I can approve
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/16846752/c97c1fa9-685b-456f-8520-050544c9fe8b)
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/16846752/a25493c7-573d-4977-a295-f6aeaf4745d6)

2024-05-29 19:27 UTC, MuhammadNSC commented
@Alzavio The height difference is due the the length of the items description

2024-05-29 19:30 UTC, Alzavio approved these changes

2024-05-29 20:50 UTC, larsswenson approved these changes
The tiles' uniformity in size significantly improves improves the UI/UX. I see this was achieved with Grid tags. As more than 2 items are added to each category, will the tiles display in rows/columns, or vertically (as it appears they are now)?

2024-05-29 21:23 UTC, keiffer213 requested changes
Let me just put a temporary hold on this before it gets merged

2024-05-30 00:22 UTC, keiffer213 approved these changes

2024-05-30 00:22 UTC, merged