belindas-closet-nextjs_08_438_Fields_category_page_02
SeattleColleges/belindas-closet-nextjs pull request #459
Opened 2024-06-12 03:57 UTC by Diego-Cano

This is a pull request!

Please fill out this description with the following:
Aims to Resolves [#438](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/438#issue-2339438044)
I am trying to set up the logic for displaying only related fields for each product.  

![Screenshot 2024-06-11 at 8 55 17 PM](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/64940291/2910462b-d756-4870-9000-df2653c43b60)

2024-06-13 07:50 UTC, alasali1 reviewed
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/77362461/f871e764-1f60-4657-902f-275162c232a1)
On my end it looks like all of the fields are missing rather than only irrelevant fields.
I would guess that most of the work to be done would be at the end starting in the <stack> element though I am not very strong in typescript. I would think that you might be able to add a line like `{product.productType === "Shoes" && (` to try and validate/compare the products productType property.
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/77362461/cde56fb8-7f6e-49b7-aaa3-2273a9305c14)

2024-06-13 21:07 UTC, kaimanasse15 commented
Works great!
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91504156/7ca0bf24-98b4-4a91-b7a2-c0397ef4a870)

2024-06-14 03:21 UTC, miqo1385 commented
it look great in my end. good job.

2024-06-14 06:07 UTC, gitbiruk2010 commented on app/category-page/[categoryId]/page.tsx
Looks a greate addition for the products to be categorized together. Code is clear  and well organized.

2024-06-14 07:09 UTC, keiffer213 approved these changes
Thanks for getting this done! It looks so much nicer having the tile's display simpler information in category pages!

![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/54779894/cea9d2fa-8192-4850-a3e2-de0c6075b0bd)

2024-06-14 08:32 UTC, intisarosman1 requested changes
I noticed that now the relevant details are also removed, so sizing for all products regardless of category are no longer shown when they should be (shoes should show shoe size, pants should show pant waist size and inseam size, etc.). I can only see the gender and description now.

![Screenshot 2024-06-14 012514](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/77607212/7031eb1b-f3c2-4e7b-a6bb-0358cb795f38)

2024-07-16 01:26 UTC, closed without merging

2024-07-16 01:26 UTC, bcko commented
@Diego-Cano Can you address this and resolve conflicts? I am going to close this pull request. Please reopen or create a new branch (whichever one is easier) when you are ready

> I noticed that now the relevant details are also removed, so sizing for all products regardless of category are no longer shown when they should be (shoes should show shoe size, pants should show pant waist size and inseam size, etc.). I can only see the gender and description now.
> 
> ![Screenshot 2024-06-14 012514](https://private-user-images.githubusercontent.com/77607212/339695523-7031eb1b-f3c2-4e7b-a6bb-0358cb795f38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTMyOTUsIm5iZiI6MTcyMTA5Mjk5NSwicGF0aCI6Ii83NzYwNzIxMi8zMzk2OTU1MjMtNzAzMWViMWItZjNjMi00ZTdiLWE2YmItMDM1OGNiNzk1ZjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDAxMjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNDQxZDExNjEyZDc0MjMyYjUxYWMzNDM3YTkwMjBkNTY4OGM1MTFiMGJkYWUwMjUyMmRkNzRhNTE2NDYyMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SXWoAATtSCGium3QOjMIFFGMNZ6U11zlfZdCeZpXILY)